name: Issue 处理

on:
  issues:
    types: [closed]

jobs:
  handle-issue:
    runs-on: windows-latest

    steps:
    - name: 检查 Issue 是否关闭
      if: github.event.action == 'closed'
      run: |
        echo "Issue has been closed."

    - name: 在关闭的 Issue 上发表评论
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const issue = context.payload.issue;
          if (issue && issue.user) {
            const commentBody = `@${issue.user.login}，你的问题已被解决，请下载最新版本进行验证，感谢你提出的问题 ❤️`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody,
            });
          } else {
            console.log("Issue or user information is missing.");
          }
